### ISSUE TITLE
Request for more inline documentation

### ISSUE THREAD

**Issue by jlieb10** [paulmg/ThreeJS-Webpack-ES6-Boilerplate#1]
Hi - I am new to Three.js and was looking for a boilerplate that would help write it in a structured way (but without a full framework) - This is a really amazing to find! However, I don't know the intricacies of Three.js and am not at expert level for ES6 syntax (particularly promises), so I am writing to request more inline documentation about what's being accomplished at each stage of your code.

Of course, no worries if you don't have time for this- I will continue to explore this codebase on my own. I just think it could be an immensely helpful learning tool if I knew more about what was going on with every method.

Many thanks!

**Comment by paulmg** [comment]
Hey,

I am glad that this might help you. I can see about adding some more comments to the code as I also realize I need to clean some parts up a bit and can therefore kill two birds with one stone. However, I would recommend that if you are new to es6 and three.js, to take a look at some examples and/or courses of each specifically before going through the code of this boilerplate. The goal of this app is more to help speed project development up rather than be an instructive tool (not that that is mutually exclusive). Regardless, I'll update the project soon with some more helpful comments.

**Comment by jlieb10** [comment]
Hey, thanks @paulmg - I look forward to seeing the code with a bit more documentation! I know it's not meant to be a learning resource but I do think it could be quite a powerful one, and this repo is the best boilerplate for those of us who want to get off the ground with a structured implementation of Three.js. Most other boilerplates and examples do not demo this library with solid, modern, production-level development.

Thanks again!
